//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action 
    {
        public Action()
        {
            this.Actions_Days = new HashSet<Actions_Days>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ResidentID { get; set; }
        public System.Guid Section_InterventionID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Occurrences { get; set; }
        public string Type { get; set; }
        public int Interval { get; set; }
        public Nullable<int> Instance { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<bool> IsAdhocIntervention { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Actions_Days> Actions_Days { get; set; }
        public virtual User User1 { get; set; }
        public virtual Resident Resident { get; set; }
        public virtual Section_Intervention Section_Intervention { get; set; }
    }
}
