//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHMEntities : DbContext
    {
        public CHMEntities()
            : base("name=CHMEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Actions_Days> Actions_Days { get; set; }
        public virtual DbSet<Intervention_Question> Intervention_Question { get; set; }
        public virtual DbSet<Intervention_Question_Answer> Intervention_Question_Answer { get; set; }
        public virtual DbSet<Intervention_Question_Answer_Task> Intervention_Question_Answer_Task { get; set; }
        public virtual DbSet<Intervention_Question_ParentQuestion> Intervention_Question_ParentQuestion { get; set; }
        public virtual DbSet<Intervention> Interventions { get; set; }
        public virtual DbSet<Interventions_Question_Answer_Summary> Interventions_Question_Answer_Summary { get; set; }
        public virtual DbSet<Interventions_Resident_Answers> Interventions_Resident_Answers { get; set; }
        public virtual DbSet<OrganizationGroup> OrganizationGroups { get; set; }
        public virtual DbSet<OrganizationGroups_Organizations> OrganizationGroups_Organizations { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Question_ParentQuestion> Question_ParentQuestion { get; set; }
        public virtual DbSet<Resident_Interventions_Questions_Answers> Resident_Interventions_Questions_Answers { get; set; }
        public virtual DbSet<Resident> Residents { get; set; }
        public virtual DbSet<Residents_Questions_Answers> Residents_Questions_Answers { get; set; }
        public virtual DbSet<Residents_Relatives> Residents_Relatives { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Section_Intervention> Section_Intervention { get; set; }
        public virtual DbSet<Section_Intervention_Statements> Section_Intervention_Statements { get; set; }
        public virtual DbSet<Section_Summary> Section_Summary { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Sections_Organizations> Sections_Organizations { get; set; }
        public virtual DbSet<Sections_Questions> Sections_Questions { get; set; }
        public virtual DbSet<Sections_Questions_Answers> Sections_Questions_Answers { get; set; }
        public virtual DbSet<Sections_Questions_Answers_Summary> Sections_Questions_Answers_Summary { get; set; }
        public virtual DbSet<Sections_Questions_Answers_Tasks> Sections_Questions_Answers_Tasks { get; set; }
        public virtual DbSet<Sections_Questions_Answers_Widget> Sections_Questions_Answers_Widget { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Users_Organizations> Users_Organizations { get; set; }
        public virtual DbSet<Users_Roles> Users_Roles { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<PainMonitoring> PainMonitorings { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
    }
}
