//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervention 
    {
        public Intervention()
        {
            this.Interventions_Resident_Answers = new HashSet<Interventions_Resident_Answers>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid Action_DayID { get; set; }
        public System.DateTime PlannedStartDate { get; set; }
        public System.DateTime PlannedEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string MoodAfter { get; set; }
        public string MoodDuring { get; set; }
        public string MoodBefore { get; set; }
        public string OutCome { get; set; }
        public string Exception { get; set; }
        public string Time_Span { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public string IsHandOverNotes { get; set; }
    
        public virtual Actions_Days Actions_Days { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Interventions_Resident_Answers> Interventions_Resident_Answers { get; set; }
    }
}
