//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PainMonitoring 
    {
        public System.Guid ID { get; set; }
        public System.Guid ResidentID { get; set; }
        public System.Guid OrganizationID { get; set; }
        public string PartsID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Resident Resident { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
