//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_ParentQuestion 
    {
        public System.Guid ID { get; set; }
        public System.Guid QuestionID { get; set; }
        public System.Guid ParentQuestionID { get; set; }
        public Nullable<System.Guid> ParentAnswerID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual Sections_Questions Sections_Questions { get; set; }
        public virtual Sections_Questions_Answers Sections_Questions_Answers { get; set; }
        public virtual Sections_Questions Sections_Questions1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
