//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section 
    {
        public Section()
        {
            this.Sections_Organizations = new HashSet<Sections_Organizations>();
            this.Sections_Questions_Answers = new HashSet<Sections_Questions_Answers>();
            this.Sections_Questions = new HashSet<Sections_Questions>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public Nullable<bool> HasScore { get; set; }
        public Nullable<bool> HasSummary { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Sections_Organizations> Sections_Organizations { get; set; }
        public virtual ICollection<Sections_Questions_Answers> Sections_Questions_Answers { get; set; }
        public virtual ICollection<Sections_Questions> Sections_Questions { get; set; }
    }
}
