//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_Summary 
    {
        public Section_Summary()
        {
            this.Interventions_Question_Answer_Summary = new HashSet<Interventions_Question_Answer_Summary>();
            this.Sections_Questions_Answers_Summary = new HashSet<Sections_Questions_Answers_Summary>();
        }
    
        public System.Guid ID { get; set; }
        public string Summary { get; set; }
        public bool IsAnswerText { get; set; }
        public Nullable<int> MaxScore { get; set; }
        public Nullable<int> MinScore { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual ICollection<Interventions_Question_Answer_Summary> Interventions_Question_Answer_Summary { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Sections_Questions_Answers_Summary> Sections_Questions_Answers_Summary { get; set; }
    }
}
