//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sections_Questions 
    {
        public Sections_Questions()
        {
            this.Question_ParentQuestion = new HashSet<Question_ParentQuestion>();
            this.Question_ParentQuestion1 = new HashSet<Question_ParentQuestion>();
            this.Sections_Questions_Answers = new HashSet<Sections_Questions_Answers>();
            this.Sections_Questions_Answers_Summary = new HashSet<Sections_Questions_Answers_Summary>();
            this.Sections_Questions_Answers_Tasks = new HashSet<Sections_Questions_Answers_Tasks>();
            this.Sections_Questions_Answers_Widget = new HashSet<Sections_Questions_Answers_Widget>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid SectionID { get; set; }
        public string Question { get; set; }
        public string QuestionView { get; set; }
        public string AnswerType { get; set; }
        public Nullable<int> MinScore { get; set; }
        public Nullable<int> MaxScore { get; set; }
        public Nullable<int> Score { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual ICollection<Question_ParentQuestion> Question_ParentQuestion { get; set; }
        public virtual ICollection<Question_ParentQuestion> Question_ParentQuestion1 { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<Sections_Questions_Answers> Sections_Questions_Answers { get; set; }
        public virtual ICollection<Sections_Questions_Answers_Summary> Sections_Questions_Answers_Summary { get; set; }
        public virtual ICollection<Sections_Questions_Answers_Tasks> Sections_Questions_Answers_Tasks { get; set; }
        public virtual ICollection<Sections_Questions_Answers_Widget> Sections_Questions_Answers_Widget { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
