//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_Intervention 
    {
        public Section_Intervention()
        {
            this.Actions = new HashSet<Action>();
            this.Intervention_Question = new HashSet<Intervention_Question>();
            this.Intervention_Question_Answer = new HashSet<Intervention_Question_Answer>();
            this.Intervention_Question_Answer_Task = new HashSet<Intervention_Question_Answer_Task>();
            this.Section_Intervention1 = new HashSet<Section_Intervention>();
            this.Section_Intervention_Statements = new HashSet<Section_Intervention_Statements>();
            this.Sections_Questions_Answers_Tasks = new HashSet<Sections_Questions_Answers_Tasks>();
        }
    
        public System.Guid ID { get; set; }
        public string InterventionTitle { get; set; }
        public string InterventionIcon { get; set; }
        public Nullable<int> MaxScore { get; set; }
        public Nullable<int> MinScore { get; set; }
        public Nullable<System.Guid> Parent_InterventionID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<Intervention_Question> Intervention_Question { get; set; }
        public virtual ICollection<Intervention_Question_Answer> Intervention_Question_Answer { get; set; }
        public virtual ICollection<Intervention_Question_Answer_Task> Intervention_Question_Answer_Task { get; set; }
        public virtual ICollection<Section_Intervention> Section_Intervention1 { get; set; }
        public virtual Section_Intervention Section_Intervention2 { get; set; }
        public virtual ICollection<Section_Intervention_Statements> Section_Intervention_Statements { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Sections_Questions_Answers_Tasks> Sections_Questions_Answers_Tasks { get; set; }
    }
}
